### ISSUE TITLE
Use a specific version of OpenFoam

### ISSUE THREAD

**Issue by r-barnes** [ZhenduoZhu/HydroSedFoam#2]
CAGEO Associate Editor Richard here.

The current installation and compilation instructions refer only to OpenFOAM, not a specific version of it.

Perhaps for this reason, I was unable to follow the instructions.

For instance, my `src` folder does not contain `turbulenceModels`, only `TurbulenceModels`. Looking in `TurbulenceModels/` I see the following (showing only relevant-seeming entries) directory structure:

    ./turbulenceModels
    ./turbulenceModels/RAS
    ./turbulenceModels/RAS/kEpsilon
    ./incompressible
    ./incompressible/lnInclude
    ./incompressible/turbulentTransportModels
    ./incompressible/turbulentTransportModels/RAS
    ./incompressible/turbulentTransportModels/RAS/LamBremhorstKE
    ./incompressible/turbulentTransportModels/RAS/kkLOmega
    ./incompressible/turbulentTransportModels/RAS/LienLeschziner
    ./incompressible/turbulentTransportModels/RAS/qZeta
    ./incompressible/turbulentTransportModels/RAS/ShihQuadraticKE
    ./incompressible/turbulentTransportModels/RAS/LienCubicKE
    ./incompressible/turbulentTransportModels/derivedFvPatchFields
    ./incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions
    ./incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions
    ./incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction
    ./incompressible/Make

It's not clear how to map from your code onto this structure.

I suggest you modify your installation instructions to work with a specific OpenFOAM docker release. The newest one seems to be `v1712`.

**Comment by ZhenduoZhu** [comment]
Hi Dr. Barnes,
Thanks a lot for your suggestion. I have added related information into README:

OpenFOAM 2.3.0 need to be installed first. This model was developed and tested with OpenFOAM 2.3.0. Please note that other versions of OpenFOAM may not have the same organization of folders and files so you may not find the folders metioned below with another version.

Information on OpenFOAM 2.3.0 can be found here: https://openfoam.org/release/2-3-0/

Regards,
Zhenduo

**Comment by r-barnes** [comment]
Thank you, Dr. Zhu,
Let's call this good, then.

For future developments your group may make concerning OpenFOAM, I'd recommend using the new docker releases: these will better ensure reproducibility and make it easier for others to use your good work. I don't believe these were available for OpenFOAM 2.3.0.
